### ISSUE TITLE
Implementing CRUD procedure

### ISSUE THREAD

**Issue by sidthesloth** [papauschek/play-slick-evolutions#1]
Hi Papauschek,

Thank you for the nice work this is absolutely great. Just have a question on how to use this to do create update and delete procedures and where would the crud code reside (was thinking in the controller package),And leave the templates to just display the data.

**Comment by papauschek** [comment]
For smaller projects it's fine if you do the Slick queries in the controller.

But for bigger projects I would suggest creating functions and classes that handle the business logic on an extra layer. A basic structure could look like this:
- Controllers: Fetch the data using the business logic layer, possibly to dome work with them, pass them to Play templates.
- Business Logic Classes+Objects: Create, Update, Deletes entities on the database using the autogenerated slick classes.
- (Autogenerated) Slick Tables: Represents the raw database tables

But this is really a more generic question about how to structure an application, and has not much to do with this project in particular (which is just about the autogenerating part). Maybe ask on the Scalaquery / Slick mailing list for better answers.

**Comment by sidthesloth** [comment]
Oh ok I realize that, anyhow thank you for the advice. great work

**Comment by papauschek** [comment]
you're welcome
