### ISSUE TITLE
Eclipse doesn't see the files

### ISSUE THREAD

**Issue by archaeron** [papauschek/play-slick-evolutions#2]
Hello

Thank you for your awesome work.

I'm using this in Eclipse and it says: object `Tables` is not a member of `db`.

I think eclipse doesn't look in the Target folder.
Do you know how I could fix this?

Thank you again :)

**Comment by papauschek** [comment]
try running "play eclipse" in your terminal to create your eclipse project.

**Comment by archaeron** [comment]
I tried that. it helped some, but Eclipse still can't see db.Tables :(

**Comment by archaeron** [comment]
okay, I've found the issue :)

you can right click on the project -> Java Build Path -> Source -> add Folder -> target/Scala-2.10/src_managed/main/db

Thanks again!
